### ISSUE TITLE
Feature request: ability to delete files with massren

### ISSUE THREAD

**Issue by 315234** [laurent22/massren#11]
For example, file names which are replaced with blank lines or some kind of flag ("DELETE_ME" etc) could be deleted rather than renamed. This would be useful for cleaning up messy directories, for example after extracting an archive in the wrong place. Could have a command line flag to turn this feature on.

**Comment by tborychowski** [comment]
this should be documented. I've spent a while looking for this. 
The main readme mentioning that it is possible, it doesn't say how...
