### ISSUE TITLE
Support for folder moving files into subfolders?

### ISSUE THREAD

**Issue by abrahamvelazquez** [laurent22/massren#18]
Are there any plans to support renaming a file with with a slash and it would create subfolders and move the files in?

`/path1_subpath1_name.jpg`

`/path1/subpath1/name.jpg`

**Comment by nmussy** [comment]
:+1: Would love that.

Also related, the ability to list files recursively, to move those around too.

**Comment by mvance** [comment]
I came here looking for just this feature tonight, trying to convert filenames exported from a CMS to a format I can use with a static site generator. A definite :+1: from me.

**Comment by laurent22** [comment]
Fixed in https://github.com/laurent22/massren/pull/20
