### ISSUE TITLE
Cannot lowercase names

### ISSUE THREAD

**Issue by abrahamvelazquez** [laurent22/massren#29]
Changing names to lowercase characters  but keeping the same name does not work.

`"/UPPERCASE NAME" cannot be renamed to "/uppercase name": destination already exists`

**Comment by laurent22** [comment]
There was indeed some issue with changing the case of a file in a case-insensitive file system. Should be fixed in the latest commit 21466d35889ad2f069f2ad5383e6b8f8e19255f8

**Comment by abrahamvelazquez** [comment]
Thank you!
