### ISSUE TITLE
`include_header` is not removing header

### ISSUE THREAD

**Issue by vitorgalvao** [laurent22/massren#34]
I’ve tried multiple variants like:

```
massren --config include_heder 0
massren --config include_heder=0
massren --config include_heder false
```

I get a message that te config has been changed and get a `0` exit code, but the header is still there when I run `massren`.

**Comment by laurent22** [comment]
You have a typo in the parameter name. The syntax should be `massren --config include_header 0`

**Comment by vitorgalvao** [comment]
Thank you. I thought I had copied it directly from the `help`, but clearly not.

Apologies for the noise.
