### ISSUE TITLE
Review/fix file name punctuation (i.e. question mark ?) breaking output list order #Bug

### ISSUE THREAD

**Issue by ldexterldesign** [laurent22/massren#37]
Hi,

Hope you're well

Thanks for software

When I process the contents of this folder the following file gets output at the bottom of the file list:

```
It's Always Sunny in Philadelphia - s04e07 - Who Pooped the Bed? 2008-10-09 - DVDRIP - SDTV-480p24 - XVID AC3.avi
```

Screen shot:

<img width="1440" alt="screenshot 2018-11-11 at 18 47 57" src="https://user-images.githubusercontent.com/1715809/48316315-79955700-e5e2-11e8-9aee-de0b04726bfc.png">

<img width="1440" alt="screenshot 2018-11-11 at 18 48 05" src="https://user-images.githubusercontent.com/1715809/48316342-81ed9200-e5e2-11e8-9b2e-30b89969fec5.png">

The oddity appears to be due to the question mark in the file name

Can this be fixed?

If you're reading this and:

a) agree, then please up-vote and/or reply +1, or;
b) disagree, then I'd love to know why?

If you have any issues (e.g. questions/queries) happy to help

Hope to hear back

Keep up great work!

Yours faithfully

hardware: Apple, MacBook Pro (Retina, 15-inch, Mid 2014)
software - operating system: macOS, v10.14 (18A391)

**Comment by ldexterldesign** [comment]
BUMP

**Comment by ldexterldesign** [comment]
BUMP

**Comment by laurent22** [comment]
? is not valid in a filename in most operating systems so i think we can ignore this bug. The till is only as good as the operating system.
