### ISSUE TITLE
Option to disable the giant message every time I do a renaming operation.

### ISSUE THREAD

**Issue by HandsomePixel** [laurent22/massren#39]
Simply put, it's annoying that every time I want to rename files, I am greeted with this enormous message about how to use the program, and would like for it to go away by default.

Plus, it can actually can be cumbersome to deal with because when I want to select something like the first column of text, I end up selecting a whole bunch of forward slashes and unneeded text.

I thought of 2 different ways of how to fix this issue:

- Add a "--notut" flag that if used, disables the message from appearing my text editor, or...
- Remember that the program was launched for the first time, so show the message once, then disable thereafter. And then probably add a "--tut" flag for those that want to read the tutorial text.

I would think that the first option would be easier to implement. Just my 2 cents.

**Comment by laurent22** [comment]
See `include_header` option.

**Comment by HandsomePixel** [comment]
Thank you for your help, and just to note, I accidentally ran "massren --help --config", and was wondering why none of the options were showing. It was because those flags were reversed, meaning they had to be in a specific order. Sorry for creating this issue...

Although I think that the "--config" flag should be a verb instead, kinda like the "commit" in "git commit", because flags are meant to be used in any order, whereas, most of the time, verbs expect an input.
