### ISSUE TITLE
`massren .`

### ISSUE THREAD

**Issue by reagle** [laurent22/massren#50]
I used to invoke with this syntax: `massren .` . But it no longer works, it shows empty. I can leave the `.` off and it'll work, but I don't know why `.` fails as a path specification...?

**Comment by reagle** [comment]
In fact, it doesn't look like any path specification works.

<img width="663" alt="Screen Shot 2022-08-13 at 19 17 07" src="https://user-images.githubusercontent.com/596814/184516364-e854a59d-f1cd-46df-a496-9e529d6328b7.png">

<img width="394" alt="Screen Shot 2022-08-13 at 19 16 56" src="https://user-images.githubusercontent.com/596814/184516367-10051cef-031e-427b-83c1-4a15b875f78c.png">

**Comment by laurent22** [comment]
The software hasn't been updated recently, so it could be some changes in your shell that's causing this.

**Comment by reagle** [comment]
Thanks! Any suggestions for testing that?
