### ISSUE TITLE
Please tag a new release

### ISSUE THREAD

**Issue by subnut** [laurent22/massren#55]
Please tag a new release containing the recent commits that replace godeps in favor of go modules

Thank you

**Comment by subnut** [comment]
Also, if possible, please update the dependencies to the latest possible version.

For example, `mattn/go-sqlite` has fixed a bug in 2016 (https://github.com/mattn/go-sqlite3/commit/f6e7921d24a633f15e039189b0c06889f0c5e4a5) that allows us to link to the system libsqlite3 instead of compiling it again.

**Comment by laurent22** [comment]
I'll see about creating a new release but i won't update the dependencies for now, unless something is broken because of it

**Comment by subnut** [comment]
Just creating a new release would be immensely helpful.

Thanks a lot.

**Comment by laurent22** [comment]
I've released a new version now: https://github.com/laurent22/massren/releases/tag/v1.5.7
